### ISSUE TITLE
Reuse same database?

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/phase-4-deploying-rails-react-to-render#1]
### Canvas Link

N/A

### Concern

Hey there! I was confused as to whether or not we were supposed to use the same PSQL database that we created in the previous "deploy a rails api" lesson. The instructions for this one seemed to imply that we were supposed to. 

If we're not, then it might be a good idea to tell students that they'll need a new database instance, which means they'll need to get rid of the old one, since Render only allows one free-tier database at a time.

My deploy failed when I tried to use the same database - not sure if that's the issue or if it's something else I did. A little clarification could help students from getting into a similar situation.

**Comment by lizbur10** [comment]
Hey @Matt-Eva - thanks for the feedback!

How to handle multiple databases is covered in [this section](https://github.com/learn-co-curriculum/phase-4-deploying-rails-api-to-render#create-the-database-on-render) in the Rails API deployment lesson (it was only pushed up yesterday so you may have seen an earlier version).

I'll leave this issue open - let me know if that resolves the problem.

**Comment by Matt-Eva** [comment]
Gotcha, thanks @lizbur10! That's exactly what happened haha.

**Comment by lizbur10** [comment]
No worries! OK if I go ahead and close this issue?
