### ISSUE TITLE
Issues With "Deploying a Rails-React App to Render" Assignment

### ISSUE THREAD

**Issue by SamuelBanya** [learn-co-curriculum/phase-4-deploying-rails-react-to-render#2]
### Canvas Link

https://learning.flatironschool.com/courses/5287/pages/deploying-a-rails-react-app-to-render?module_item_id=494236

### Concern
**Zero Mentioning Of "Ruby" For Deployment:**
As this project is a React project, it defaulted to "Node' for the 'Environment' when a new 'Web Service' is attempted to be created on Render.com.

Your team needs to make a revision to mention that it needs to be "Ruby" for the "Environment" since if you try to deploy it without changing it to "Ruby" and keep it as "Node", it will provide an error, "[Bundle not found](build.sh: line 11: bundle: command not found)"

Related screenshot:
![2022-12-20 11_24_23-Window](https://user-images.githubusercontent.com/90813277/208728714-568f580d-8457-4bce-b9eb-85d068bb5e5f.png)

**Comment by lizbur10** [comment]
Hi @SamuelBanya! Thanks for submitting this feedback. Step #5 in the "Deploy to Render" section included an instruction to set the Environment to Ruby, but I can see why it was easy to miss that. I tried to make it a little more apparent by separating that step into two sub-steps instead. Hope that helps!

Thanks for contributing to the Flatiron School curriculum 💙
